baseURL = 'https://blog.tudorandrei.xyz'
languageCode = 'en-us'
title = "TudorAndrei's Blog"
theme = "archie"
copyright = "TudorAndrei"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 5

[params]
  mode = "toggle"
  description = "Welcome to my blog"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/tudorandrei"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:tudorandrei.dumitrascu@gmail.com"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/tudor-pythia/"
